name: check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Generate question_type.json
        run: python scripts/generate_question_type.py
